# Generated by Django 4.0.6 on 2023-02-01 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqfeatureQualifierValue',
            fields=[
                ('seqfeature_qualifiervalue_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
                ('value', models.TextField()),
                ('seqfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='bioseq.seqfeature')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioseq.term')),
            ],
            options={
                'db_table': 'seqfeature_qualifier_value',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='TermDbxref',
        ),
        migrations.AddIndex(
            model_name='seqfeaturequalifiervalue',
            index=models.Index(fields=['term'], name='seqfeature__term_id_9085a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seqfeaturequalifiervalue',
            unique_together={('seqfeature', 'term', 'rank')},
        ),
    ]
