# Generated by Django 4.0.6 on 2023-02-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0002_seqfeaturequalifiervalue_delete_termdbxref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioentryDbxref',
            fields=[
                ('bioentry_dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
                ('bioentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbxrefs', to='bioseq.bioentry')),
                ('dbxref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioseq.dbxref')),
            ],
            options={
                'db_table': 'bioentry_dbxref',
                'managed': True,
                'unique_together': {('bioentry', 'dbxref', 'rank')},
            },
        ),
    ]
