# Generated by Django 4.0.6 on 2023-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0004_biodatabasequalifiervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='node_division',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='scientificName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
