# Generated by Django 4.2.4 on 2023-08-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0005_taxon_node_division_taxon_scientificname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermDbxref',
            fields=[
                ('term_dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
                ('dbxref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioseq.dbxref')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbxrefs', to='bioseq.term')),
            ],
            options={
                'db_table': 'term_dbxref',
                'managed': True,
                'unique_together': {('term', 'dbxref')},
            },
        ),
    ]
