# Generated by Django 4.2.4 on 2023-08-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0006_termdbxref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termdbxref',
            name='dbxref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='terms', to='bioseq.dbxref'),
        ),
    ]
