# Generated by Django 4.2.4 on 2023-08-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0008_alter_bioentry_accession_termrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='identifier',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.TextField(blank=True, default='x'),
            preserve_default=False,
        ),
    ]
